# CONFIGURACIÓN DEL SERVIDOR WEB - PRODUCCIÓN
# Autor: Jorge Oscanoa

# 1. Reglas de Puertos
ALLOW PORT 80/tcp   (HTTP - Web Normal)
ALLOW PORT 443/tcp  (HTTPS - Web Segura)
ALLOW PORT 22/tcp   (SSH - Para Admin)

# 2. Bloqueos
DENY PORT 21        (FTP - Inseguro)
DENY ALL OTHERS     (Cerrar el resto)

